spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/taskboard_db
    username: postgres
    password: Test1234=
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:/db/migration

app:
  jwt:
    secret: "${JWT_SECRET:my-super-secret}"
